import Head from "next/head";
import Image from "next/image";
import homeStyles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Kimhsr</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://static-00.iconduck.com/assets.00/next-js-icon-512x512-zuauazrk.png"
        />
      </Head>
      <section className={homeStyles.headingMd}>
        <p>[Kimhsr Introduction]</p>
        <p>(This is a website)</p>
      </section>
      <section className={`${homeStyles.headingMd} ${homeStyles.padding1px}`}>
        <h2 className={homeStyles.headingLg}>Blog</h2>
        <ul className={homeStyles.list}></ul>
      </section>
    </div>
  );
}
