import { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { getSortedPostsData } from "../lib/posts";
import homeStyles from "../styles/Home.module.css";

const Home = ({
  allPostsData,
}: {
  allPostsData: {
    date: string;
    title: string;
    id: string;
  }[];
}) => {
  return (
    <div className={homeStyles.container}>
      <Head>
        <title>Kimhsr</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://static-00.iconduck.com/assets.00/next-js-icon-512x512-zuauazrk.png"
        />
      </Head>
      <section className={homeStyles.headingMd}>
        <p>[Kimhsr Introduction]</p>
        <p>(This is a website)</p>
      </section>
      <section className={`${homeStyles.headingMd} ${homeStyles.padding1px}`}>
        <h2 className={homeStyles.headingLg}>Blog</h2>
        <ul className={homeStyles.list}></ul>
        {allPostsData.map(({ id, title, date }) => (
          <li className={homeStyles.listItem} key={id}>
            <Link href={`/posts/${id}`}>{title}</Link>
            <br />
            <small className={homeStyles.lightText}>{date}</small>
          </li>
        ))}
      </section>
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
    },
  };
};
